# Buildsheet autogenerated by ravenadm tool -- Do not edit.

NAMEBASE=		ruby-http_parser.rb
VERSION=		0.8.0
KEYWORDS=		ruby
VARIANTS=		v30 v31 v32
SDESC[v30]=		Simple callback-based HTTP request/response (v30)
SDESC[v31]=		Simple callback-based HTTP request/response (v31)
SDESC[v32]=		Simple callback-based HTTP request/response (v32)
HOMEPAGE=		https://github.com/tmm1/http_parser.rb
CONTACT=		Ruby_Automaton[ruby@ironwolf.systems]

DOWNLOAD_GROUPS=	main
SITES[main]=		RUBYGEMS/
DISTFILE[1]=		http_parser.rb-0.8.0.gem:main
DIST_SUBDIR=		ruby
DF_INDEX=		1
SPKGS[v30]=		single
SPKGS[v31]=		single
SPKGS[v32]=		single

OPTIONS_AVAILABLE=	RUBY30 RUBY31 RUBY32
OPTIONS_STANDARD=	none
VOPTS[v30]=		RUBY30=ON RUBY31=OFF RUBY32=OFF
VOPTS[v31]=		RUBY30=OFF RUBY31=ON RUBY32=OFF
VOPTS[v32]=		RUBY30=OFF RUBY31=OFF RUBY32=ON

DISTNAME=		http_parser.rb-0.8.0

GENERATED=		yes

[RUBY30].USES_ON=			gem:v30

[RUBY31].USES_ON=			gem:v31

[RUBY32].USES_ON=			gem:v32

[FILE:107:descriptions/desc.single]
Ruby bindings to https://github.com/joyent/http-parser and
https://github.com/http-parser/http-parser.java


[FILE:108:distinfo]
5a0932f1fa82ce08a8516a2685d5a86031c000560f89946913c555a0697544be       195072 ruby/http_parser.rb-0.8.0.gem

