# Buildsheet autogenerated by ravenadm tool -- Do not edit.

NAMEBASE=		ruby-http_parser.rb
VERSION=		0.8.1
KEYWORDS=		ruby
VARIANTS=		v33 v34 v40
SDESC[v40]=		Http-parser bindings (v40)
SDESC[v33]=		Http-parser bindings (v33)
SDESC[v34]=		Http-parser bindings (v34)
HOMEPAGE=		https://github.com/tmm1/http_parser.rb
CONTACT=		Ruby_Automaton[ruby@ironwolf.systems]

DOWNLOAD_GROUPS=	main
SITES[main]=		RUBYGEMS/
DISTFILE[1]=		http_parser.rb-0.8.1.gem:main
DIST_SUBDIR=		ruby
DF_INDEX=		1
SPKGS[v40]=		single
SPKGS[v33]=		single
SPKGS[v34]=		single

OPTIONS_AVAILABLE=	RUBY33 RUBY34 RUBY40
OPTIONS_STANDARD=	none
VOPTS[v40]=		RUBY33=OFF RUBY34=OFF RUBY40=ON
VOPTS[v33]=		RUBY33=ON RUBY34=OFF RUBY40=OFF
VOPTS[v34]=		RUBY33=OFF RUBY34=ON RUBY40=OFF

DISTNAME=		http_parser.rb-0.8.1

GENERATED=		yes

[RUBY40].USES_ON=			gem:v40

[RUBY33].USES_ON=			gem:v33

[RUBY34].USES_ON=			gem:v34

[FILE:107:descriptions/desc.single]
Ruby bindings to https://github.com/joyent/http-parser and
https://github.com/http-parser/http-parser.java


[FILE:108:distinfo]
9ae8df145b39aa5398b2f90090d651c67bd8e2ebfe4507c966579f641e11097a       188416 ruby/http_parser.rb-0.8.1.gem

