# Autogenerated -- Do not edit!
# Provide default versions for ports with multiple versions selectable
# by the user.
#
# Users who want to override these defaults can easily do so by defining
# DEFAULT_VERSIONS in their make.conf as follows:
#
# DEFAULT_VERSIONS=	perl5=5.36 ruby=3.2
#

.if !defined(_INCLUDE_BSD_DEFAULT_VERSIONS_MK)
_INCLUDE_BSD_DEFAULT_VERSIONS_MK=	yes

.  for base in LUA MYSQL PERL5 PHP PGSQL PYTHON3 RUBY SSL TCL
.undef ${base}_DEFAULT
.  endfor

.  for base in ${DEFAULT_VERSIONS}
_l=			${base:C/=.*//g}
${_l:tu}_DEFAULT=	${base:C/.*=//g}
.  endfor

#-------------------------------------------------------------------------
# PERL5
# Possible values: 5.40 and 5.42
#-------------------------------------------------------------------------

PERL5_DEFAULT?=		5.40

PERL_5.40_VERSION=	5.40.3
PERL_5.42_VERSION=	5.42.0

#-------------------------------------------------------------------------
# RUBY
# Possible values: 3.3, 3.4, 4.0
#-------------------------------------------------------------------------

RUBY_DEFAULT?=		3.4

RUBY_3.3_VERSION=	3.3.10
RUBY_3.4_VERSION=	3.4.8
RUBY_4.0_VERSION=	4.0.1

#-------------------------------------------------------------------------
# PYTHON
# Possible values: 3.13, 314
#-------------------------------------------------------------------------

PYTHON3_DEFAULT?=	3.13

PYTHON_3.13_VERSION=	3.13.12
PYTHON_3.14_VERSION=	3.14.3

PIP_3.13_VERSION=	25.3
PIP_3.14_VERSION=	25.3

#-------------------------------------------------------------------------
# SSL
# Possible values: openssl30, libressl, libressl-devel
#-------------------------------------------------------------------------

SSL_DEFAULT?=		libressl

#-------------------------------------------------------------------------
# LUA
# Possible values: 5.2, 5.3, 5.4, 5.5
#-------------------------------------------------------------------------

LUA_DEFAULT?=		5.4

LUA_5.2_VERSION=	5.2.4
LUA_5.3_VERSION=	5.3.6
LUA_5.4_VERSION=	5.4.8
LUA_5.5_VERSION=	5.5.0

#-------------------------------------------------------------------------
# TCL/TK
# Possible values: 8.6, 9.0
#-------------------------------------------------------------------------

TCL_DEFAULT?=		8.6

TCL_8.6_VERSION=	8.6.16
TCL_9.0_VERSION=	9.0.3

#-------------------------------------------------------------------------
# PGSQL
# Possible values: 14, 15, 16, 17, 18
#-------------------------------------------------------------------------

PGSQL_DEFAULT?=		17

PGSQL_14_VERSION=	14.20	# EOL 12 NOV 2026
PGSQL_15_VERSION=	15.15	# EOL 11 NOV 2027
PGSQL_16_VERSION=	16.11	# EOL 09 NOV 2028
PGSQL_17_VERSION=	17.7	# EOL 08 NOV 2029
PGSQL_18_VERSION=	18.1	# EOL 14 NOV 2030

#-------------------------------------------------------------------------
# MYSQL and derivatives
# Possible values: oracle-(8.0,8.4),innovation,mariadb(,-10.6, -10.11, -11.[48])
#
# MariaDB releases:
#   MariaDB 10.6   EOL 06 JUL 2026 (STABLE-LTS)
#   MariaDB 10.11  EOL 16 Feb 2028 (STABLE-LTS)
#   MariaDB 11.4   EOL 29 May 2029 (STABLE-LTS)
#   MariaDB 11.8   EOL 04 JUN 2028 (STABLE-LTS)
#   MariaDB 12.0   EST     Q3 2025 (12.3 EST LTS)
#   MariaDB 13.0   EST     Q3 2026 (13.3 EST LTS)
#   MariaDB 14.0   EST     Q3 2027 (14.3 EST LTS)
#-------------------------------------------------------------------------

MYSQL_DEFAULT=			oracle-8.0

MYSQL_oracle-8.0_VERSION=	8.0.45
MYSQL_oracle-8.4_VERSION=	8.4.8
MYSQL_innovation_VERSION=	9.6.0
MYSQL_mariadb-10.6_VERSION=	10.6.25
MYSQL_mariadb-10.11_VERSION=	10.11.16
MYSQL_mariadb-11.4_VERSION=	11.4.10
MYSQL_mariadb-11.8_VERSION=	11.8.6
MYSQL_mariadb-BE_VERSION=	12.1.2		# Bleeding Edge

#-------------------------------------------------------------------------
# PHP (restricted to branches still receiving updates)
# Possible values: 8.3, 8.4, 8.5
#-------------------------------------------------------------------------

PHP_DEFAULT?=		8.4

PHP_8.3_VERSION=	8.3.30
PHP_8.4_VERSION=	8.4.17
PHP_8.5_VERSION=	8.5.2

#-------------------------------------------------------------------------
# Ravenports system root versions per platform
# Format: ID=opsys/arch/stdarch/os-version/os-release/os-major
#-------------------------------------------------------------------------

PLATFORM_FreeBSD_x86-64=	FreeBSD/amd64/x86_64/1402000/14.2/14
PLATFORM_DragonFly_x86-64=	DragonFly/x86_64/x86_64/600400/6.4/6.4
PLATFORM_Linux_x86-64=		Linux/x86_64/x86_64/610000/6.1.0/6.1
PLATFORM_SunOS_x86-64=		SunOS/i86pc/x86_64/151054/5.11/5.11
PLATFORM_MacOS_x86-64=		Darwin/x86_64/x86_64/170700/17.7.0/17
PLATFORM_NetBSD_x86-64=		NetBSD/x86_64/x86_64/902000000/10.0/10
PLATFORM_MidnightBSD_x86-64=	MidnightBSD/amd64/x86_64/300005/3.0.0/3
PLATFORM_OpenBSD_x86-64=	OpenBSD/amd64/x86_64/tbd/tbd/tbd

#-------------------------------------------------------------------------
# To support old system roots
#-------------------------------------------------------------------------

PREVIOUS_DF64_R62=		DragonFly/x86_64/x86_64/600200/6.2/6.2
PREVIOUS_Linux_K44=		Linux/x86_64/x86_64/440053/4.4.0/4.4
PREVIOUS_FBSD64_R13=		FreeBSD/amd64/x86_64/1302001/13.2/13

.endif # defined (_INCLUDE_BSD_DEFAULT_VERSIONS_MK)
