# Buildsheet autogenerated by ravenadm tool -- Do not edit.

NAMEBASE=		python-boolean.py
VERSION=		4.0
KEYWORDS=		python
VARIANTS=		v12 v13
SDESC[v12]=		Boolean expression and algebra library (3.12)
SDESC[v13]=		Boolean expression and algebra library (3.13)
HOMEPAGE=		https://github.com/bastikr/boolean.py
CONTACT=		Python_Automaton[python@ironwolf.systems]

DOWNLOAD_GROUPS=	main
SITES[main]=		PYPIWHL/3f/02/6389ef0529af6da0b913374dedb9bbde8eabfe45767ceec38cc37801b0bd
DISTFILE[1]=		boolean.py-4.0-py3-none-any.whl:main
DIST_SUBDIR=		python-src
DF_INDEX=		1
SPKGS[v12]=		single
SPKGS[v13]=		single

OPTIONS_AVAILABLE=	PY312 PY313
OPTIONS_STANDARD=	none
VOPTS[v12]=		PY312=ON PY313=OFF
VOPTS[v13]=		PY312=OFF PY313=ON

DISTNAME=		boolean.py-4.0.dist-info

GENERATED=		yes

[PY312].USES_ON=			python:v12,wheel

[PY313].USES_ON=			python:v13,wheel

[FILE:602:descriptions/desc.single]


This library helps you deal with boolean expressions and algebra with
variables
and the boolean functions AND, OR, NOT.

You can parse expressions from strings and simplify and compare
expressions.
You can also easily create your custom algreba and mini DSL and create
custom
tokenizers to handle custom expressions.

For extensive documentation look either into the docs directory or view it
online, at
https://booleanpy.readthedocs.org/en/latest/

https://github.com/bastikr/boolean.py

Copyright (c) 2009-2020 Sebastian Kraemer, basti.kr@gmail.com and others
SPDX-License-Identifier: BSD-2-Clause


[FILE:121:distinfo]
2876f2051d7d6394a531d82dc6eb407faa0b01a0a0b3083817ccd7323b8d96bd        25909 python-src/boolean.py-4.0-py3-none-any.whl

